# Generated by Django 5.1 on 2025-01-27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0029_blogmark_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogmark",
            name="use_markdown",
        ),
    ]
