# Generated by Django 5.1.4 on 2025-11-18 15:35

import datetime
import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0030_remove_blogmark_use_markdown"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quoteback",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(default=datetime.datetime.utcnow)),
                ("slug", models.SlugField(max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "search_document",
                    django.contrib.postgres.search.SearchVectorField(null=True),
                ),
                ("import_ref", models.TextField(max_length=64, null=True, unique=True)),
                ("card_image", models.CharField(blank=True, max_length=128, null=True)),
                ("is_draft", models.BooleanField(default=False)),
                (
                    "quote_text",
                    models.TextField(help_text="The quoted text from the source"),
                ),
                (
                    "source_url",
                    models.URLField(help_text="URL of the source page", max_length=512),
                ),
                (
                    "page_title",
                    models.CharField(
                        help_text="Title of the source page (auto-fetched)",
                        max_length=512,
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        blank=True,
                        help_text="Author name (if available)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True,
                        help_text="Favicon from the source site (auto-fetched)",
                        null=True,
                        upload_to="quotebacks/favicons/",
                    ),
                ),
                (
                    "commentary",
                    models.TextField(
                        blank=True, help_text="Your commentary on the quote"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional title for this quoteback post",
                        max_length=255,
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="blog.series",
                    ),
                ),
                ("tags", models.ManyToManyField(blank=True, to="blog.tag")),
            ],
            options={
                "verbose_name_plural": "Quotebacks",
                "ordering": ("-created",),
                "abstract": False,
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["search_document"],
                        name="blog_quoteb_search__1faf01_gin",
                    )
                ],
            },
        ),
    ]
