# Generated by Django 5.1.4 on 2025-11-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0031_quoteback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quoteback",
            name="commentary",
            field=models.TextField(
                blank=True, default="", help_text="Your commentary on the quote"
            ),
        ),
        migrations.AlterField(
            model_name="quoteback",
            name="page_title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Title of the source page (auto-fetched)",
                max_length=512,
            ),
        ),
    ]
